<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><img class="img-rounded center-block" style="margin: 3% 0 0 -3%; width: 100%; position: relative;" src="<?=WEB_DIR?>/images/logo.png"></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">

      <div class="profile_info">
      
        <h2>ISO 2015</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br />
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          
          <li>
            <a href="<?=WEB_DIR?>bg/home/"><i class="fa fa-home"></i>1. Home<span class="fa"></span></a>
          </li>
          
          
          <li><a><i class="fa fa-home"></i>2. Information about the organization<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="<?=WEB_DIR?>bg/information/name-location/">2.1 Name, location, means</a>
                <ul class="nav child_menu">
                  <li><a href="<?=WEB_DIR?>bg/installations/">2.2 History of the company</a></li>
                </ul>
              
              </li>
              <li><a href="<?=WEB_DIR?>bg/information/name-location/">2.3 Company background</a></li>
            </ul>
          </li>
          
          
          <li><a><i class="fa fa-windows"></i>3. QMS Scope<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="<?=WEB_DIR?>bg/client-patches/">3.1 General scope</a>
                <ul class="nav child_menu">
                  <li><a href="<?=WEB_DIR?>bg/installations/">3.1.1 Bla bla QMS</a></li>
                </ul>
              
              </li>
              <li><a href="<?=WEB_DIR?>bg/installations/">3.2 Application of QMS</a></li>
            </ul>
          </li>
          
          
       </ul>
      </div>
    </div>
    <!-- /sidebar menu -->

  </div>
</div>