<body>
<?php new baseTemplater('baseNavigator.tpl.inc', 'publish'); ?>
<div class="container">
  <div class="page-header">
   <h1>Error - 404</h1>
    <h3>404 - WE'RE SORRY, THE PAGE YOU REQUESTED WAS NOT FOUND</h3>
    <p> We'are sorry, the page you requested was not found.
     We have recordered this error (404) to help us fix the problem. 
     You may wish to try again using correct links.</p>
  </div>
</div>
<?php new baseTemplater('baseFooter.tpl.inc', 'publish');