<div class="top_nav">
  <div class="nav_menu">
   <nav>
     <div class="nav toggle">
       <a id="menu_toggle"><i class="fa fa-bars"></i></a>
     </div>

     <ul class="nav navbar-nav navbar-right">
       <li role="presentation" class="dropdown">
         <h2> <b> Quality Manual ISO 2015 </b>  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;</h2>           
       </li>
     </ul>
    </nav>
  </div>
</div>