<!DOCTYPE html>
<html lang="en">
<!-- Header -->
<?php $this->header->publish();?>

<!-- /Header -->

  <body class="nav-md">
    <div class="container body">
      
      
      <div class="main_container">
        <!-- Side bar -->
        <?php $this->sideBar->publish();?>
        <?php //exit;?>
        <!-- /Side bar -->
        <!-- top navigation -->
        <?php $this->topNav->publish(); ?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">


         

     
 <div class="mainBody">
  <h1>Presentation of the company</h1>
  <h2>Name </h2>
  <p>Codix Bulgaria SJSC</p>
  <h2>Location</h2>
  <p><strong>Residence and Management address:<br />
  </strong>&#8470;1 Business Park Sofia Str.,<br />
    Building 2, 1st floor, office 701<br />
&ldquo;Mladost&rdquo; qu., &ldquo;Mladost&rdquo; 4 res. qu.,<br />
    Business Park Sofia Complex<br />
    1766 Sofia<br />
    BULGARIA  </p>
  <p>ECN: 2198120134<br />
    Bulstat N: 121756.27 </p>
  <p><strong>Having as a subject of activity: </strong><br />
    System  products&rsquo; development, systems&rsquo; integration, education, consultations and  expertise, as well as every other activity, not forbidden by law.</p>
  <p><strong>The Company is represented by the Managing Director:</strong><br />
  Dimo Jelev Avdjiev</p>
  <h2>Communication means</h2>
  <p>
  <strong>Tel:</strong> +359 2 915 09 00<br />
  <strong>Fax:</strong> +359 2 975 33 17<br />
  <strong>E-mail:</strong> <a href="mailto:admoffice@imx.fr">admoffice@imx.fr</a>, <a href="mailto:hotline@imx.fr">hotline@imx.fr</a>
  </p>
    <p><div class="clear">&nbsp;</div></p>
  </div>



        </div>
        <!-- /page content -->

        <!-- footer content -->
        <?php $this->footer->publish(); ?>
        <!-- /footer content -->
      </div>
    </div>
     <?php $this->vendorLibraries->publish(); ?>
    
	
  </body>
</html>
